# ======= Gradle =======
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# ======= Kotlin =======
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true

# =========== Publishing ===========
systemProp.org.gradle.internal.publish.checksums.insecure=true
# Increase timeout when pushing to Sonatype (otherwise we get timeouts)
systemProp.org.gradle.internal.http.socketTimeout=120000

# Coordinates
GROUP=io.github.w2sv

POM_NAME=Composed
POM_DESCRIPTION=A collection of utils to facilitate development with Compose Multiplatform
POM_INCEPTION_YEAR=2024
POM_URL=https://github.com/w2sv/Composed

# Project info
POM_SCM_URL=https://github.com/w2sv/Composed
POM_SCM_CONNECTION=scm:git:git://github.com/w2sv/Composed.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/w2sv/Composed.git

# License
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

# Developer
POM_DEVELOPER_ID=w2sv
POM_DEVELOPER_NAME=Janek Zangenberg
POM_DEVELOPER_URL=https://github.com/w2sv

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true
