name: Build
on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

            -   name: Setup JDK
                uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
                with:
                    java-version: 17
                    distribution: temurin

            -   name: Build
                run: ./gradlew build
